# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=300)),
                ('output', models.CharField(max_length=300)),
            ],
        ),
    ]
