# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WinRemote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ip',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
