# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WinRemote', '0002_history_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 2, 13, 31, 17, 357000, tzinfo=utc)),
        ),
    ]
