# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WinRemote', '0004_auto_20170302_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 6, 12, 32, 32, 143000, tzinfo=utc)),
        ),
    ]
